use-grammars = { only = ["chuck"] }

[[language]]
name = "chuck"
comment-tokens = "//"
file-types = ["ck"]
scope = "source.chuck"

[[grammar]]
name = "chuck"
source = { git = "https://github.com/tymbalodeon/tree-sitter-chuck.git", rev = "52951773c84ec72fdb9671aa9d3729d407076a9b" }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "txt"
file-types = ["txt"]
indent = { tab-width = 2, unit = " " }
scope = "text.txt"
