use-grammars = { only = ["chuck"] }

[[language]]
name = "chuck"
comment-tokens = "//"
file-types = ["ck"]
scope = "source.chuck"

[[grammar]]
name = "chuck"
source = { git = "https://github.com/tymbalodeon/tree-sitter-chuck.git", rev = "44d947bf0004654081043c2422a5669779e5c32d" }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "txt"
file-types = ["txt"]
indent = { tab-width = 2, unit = " " }
scope = "text.txt"
