"do" @keyword.control.repeat
"fun" @keyword.function
"function" @keyword.function
"if" @keyword.control.conditionl
"repeat" @keyword.control.repeat
"return" @keyword.control.return
"until" @keyword.control.repeat
"while" @keyword.control.repeat

(boolean_literal_value) @constant.builtin.boolean
(chuck_operator) @operator
(class_identifier) @type
(comment) @comment
(duration_identifier) @type
(float) @constant.numeric.float
(global_unit_generator) @variable.builtin
(hexidecimal) @constant.numeric
(int) @constant.numeric.integer
(keyword) @keyword
(operator) @operator
(primitive_type) @type.builtin
(special_literal_value) @constant.builtin
(string) @string
