(chuck_operator) @operator
(class_identifier) @label
(comment) @comment
(duration_identifier) @type
(float) @constant.numeric.float
(global_unit_generator) @variable.builtin
(hexidecimal) @constant.numeric
(int) @constant.numeric.integer
(keyword) @keyword
(operator) @operator
(primitive_type) @type
(string) @string
